on: [pull_request]
name: tests
env:
  GO111MODULE: on

jobs:
  unit-tests:
    strategy:
      matrix:
        go-version: [1.15.x]
        platform: [macos-latest, ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go-version }}
      - uses: actions/checkout@v2

      - name: Cache go modules
        uses: actions/cache@v1
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('go.sum') }}
          restore-keys: ${{ runner.os }}-go-

      # - name: Run unit tests
      #   run: ./scripts/ci.sh

      - name: Test State - Race
        run: make test-state-race

      - name: Run build
        run: make build

  # publish-code-coverage:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/setup-go@v1
  #       with:
  #         go-version: ${{ matrix.go-version }}
  #     - uses: actions/checkout@v2

  #     - name: Cache go modules
  #       uses: actions/cache@v1
  #       with:
  #         path: ~/go/pkg/mod
  #         key: ${{ runner.os }}-go-${{ hashFiles('go.sum') }}
  #         restore-keys: ${{ runner.os }}-go-

  #     - name: Publish code coverage
  #       uses: paambaati/codeclimate-action@v2.7.5
  #       env:
  #         CC_TEST_REPORTER_ID: abdad8b2e2ec0bfdd7af57d955c44e9470f4d174e744b824047f3037800f5b40
  #       with:
  #         coverageCommand: go test -short -coverprofile c.out ./...
  #         prefix: github.com/ChainSafe/gossamer
  #         debug: true

  stable-tests:
    runs-on: ubuntu-latest
    steps:
      -
        name: Run stable tests
        run: |
          make it-stable
  docker-rpc-tests:
    runs-on: ubuntu-latest
    steps:
      -
        name: Run rpc tests
        run: |
          make it-rpc
  stress-tests:
    runs-on: ubuntu-latest
    steps:
      -
        name: Run stress
        run: |
          make it-stress
  grandpa-tests:
    runs-on: ubuntu-latest
    steps:
      -
        name: Run stress
        run: |
          make it-grandpa